name: C++ Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y g++

    - name: Build
      working-directory: ./numbergame 
      run: |
        g++ Source.cpp -o game
        ./game <<< "50"  # Тест с вводом числа 50