name: C++ Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y g++

    - name: Build
      run: g++ Source.cpp -o game

    - name: Run test
      run: |
        ./game <<< "50"  # Простейший тест с вводом числа 50
        ./game <<< "75"  # Дополнительный тест